### ISSUE TITLE
Error running jekyll

### ISSUE THREAD

**Issue by bangen** [Riverscapes/riverscapes-jekyll-theme#3]
I'm editing the webpage for a new riverscapes repo (see [here](https://github.com/Riverscapes/GeomorphicUpscale)).  I copied over the pertinent docs folder files from this repo.  

As I'm making a lot of changes, I'd like to check my edits using a port rather than pushing to git, waiting for the changes to post, etc.  I've done this numerous times before for our 'old' themed pages using bash and jekyll-serve following the steps in [this documentation](http://riverscapes.northarrowresearch.com/Technical_Reference/jekyll_toolbox.html).  When I tried running jekyll-serve for the new theme I ran an error (message at the bottom).  Any ideas?

```
C:\etal\Git\Riverscapes\GeomorphicUpscale\docs>bash
root@whtnlab-6mchhk2:/mnt/c/etal/Git/Riverscapes/GeomorphicUpscale/docs# jekyll serve
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:289:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll-remote-theme' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:257:in `each'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:257:in `verify_gemfile_dependencies_are_found!'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:48:in `start'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:22:in `resolve'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/definition.rb:257:in `resolve'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
        from /var/lib/gems/2.3.0/gems/jekyll-3.7.0/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from /var/lib/gems/2.3.0/gems/jekyll-3.7.0/exe/jekyll:11:in `<top (required)>'
        from /usr/local/bin/jekyll:22:in `load'
        from /usr/local/bin/jekyll:22:in `<main>'
root@whtnlab-6mchhk2:/mnt/c/etal/Git/Riverscapes/GeomorphicUpscale/docs#

**Comment by philipbaileynar** [comment]
This issue was caused by the migration to the new centralized Jekyll template. It was anticipated and we went ahead regardless because the benefits of using a centralized template outweigh the downside that there's now an extra step for those wishing to run the sites locally.

To get the sites running locally you will need a Gem file installed on your system. We haven't had time to document the steps on Windows yet, so bear with us for a few more days and we will get round to it. I'll link the documentation here.

In the meantime, I recommend using a markdown editor with preview capability such as Typora, PyCharm or Visual Studio Code. These tools won't be able to preview the page using the riverscapes theme, but they will at least give you a presentational representation of the markdown to ensure that you have the correct formatting (headers, bullets etc).
